# Generated by Django 5.2.6 on 2025-09-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cust_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(blank=True, max_length=255, null=True)),
                ('emladdr', models.EmailField(blank=True, max_length=254, null=True)),
                ('ph_num', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_ln1', models.CharField(blank=True, max_length=255, null=True)),
                ('addr_ln2', models.CharField(blank=True, max_length=255, null=True)),
                ('cty', models.CharField(blank=True, max_length=100, null=True)),
                ('st', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('cntry', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, null=True)),
                ('lst_login', models.DateTimeField(blank=True, null=True)),
                ('is_actv', models.BooleanField(default=True)),
                ('cust_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cust_data',
            },
        ),
        migrations.CreateModel(
            name='EMP_RECORDS',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EMP_RECORDS',
            },
        ),
        migrations.CreateModel(
            name='prod_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col1', models.CharField(blank=True, max_length=255, null=True)),
                ('col2', models.TextField(blank=True, null=True)),
                ('col3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('col4', models.CharField(blank=True, max_length=100, null=True)),
                ('col5', models.CharField(blank=True, max_length=50, null=True)),
                ('col6', models.IntegerField(blank=True, null=True)),
                ('col7', models.CharField(blank=True, max_length=20, null=True)),
                ('col8', models.BooleanField(default=True)),
                ('col9', models.DateTimeField(blank=True, null=True)),
                ('col10', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'prod_tbl',
            },
        ),
        migrations.CreateModel(
            name='sales_data_2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a1', models.CharField(blank=True, max_length=100, null=True)),
                ('b2', models.CharField(blank=True, max_length=100, null=True)),
                ('c3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('d4', models.IntegerField(blank=True, null=True)),
                ('e5', models.DateField(blank=True, null=True)),
                ('f6', models.CharField(blank=True, max_length=50, null=True)),
                ('g7', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('h8', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sales_data_2023',
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('actual_meaning', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_values', models.TextField(blank=True, null=True)),
                ('data_quality_issues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'database_schema',
                'unique_together': {('table_name', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='Order_History',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('order_date_time', models.DateTimeField(blank=True, null=True)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_addr', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('customer_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cust_data')),
            ],
            options={
                'db_table': 'Order_History',
            },
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ORDER_REF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order_history')),
                ('product_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prod_tbl')),
            ],
            options={
                'db_table': 'orderitems',
            },
        ),
    ]
