# Generated by Django 5.2.6 on 2025-09-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet_count', models.IntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('processing_errors', models.TextField(blank=True, null=True)),
                ('data_quality_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
        migrations.CreateModel(
            name='FileSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('original_sheet_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('has_header', models.BooleanField(default=True)),
                ('header_row', models.IntegerField(default=0)),
                ('data_start_row', models.IntegerField(default=1)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='api.uploadedfile')),
            ],
            options={
                'db_table': 'file_sheets',
            },
        ),
    ]
